name: Testing & Code analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v ./cmd/mittwald-go-client-builder

      - name: Vet
        run: go vet -v ./...

      - name: Test
        run: go test -v ./...
